# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "turbo_confirm", to: "turbo_confirm.js"
pin "offline_queue", to: "offline_queue.js"
pin "slider_track", to: "slider_track.js"
pin "photo_input", to: "photo_input.js"
pin "image_downscale", to: "image_downscale.js"
pin "units", to: "units.js"
pin "nested_fields", to: "nested_fields.js"
pin "preparation_rows", to: "preparation_rows.js"
pin "form_snapshot", to: "form_snapshot.js"
pin "pwa_install", to: "pwa_install.js"
